name: provider_setup
description: Provider Setup Tool
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  async: ^2.10.0
  flutter:
    sdk: flutter
  handy_window: ^0.3.0
  http: ^1.1.0
  meta: ^1.8.0
  provider: ^6.0.5
  safe_change_notifier: ^0.3.1
  ubuntu_service: ^0.3.0
  url_launcher: ^6.1.8
  yaru: ^1.2.0
  yaru_icons: ^2.2.2
  yaru_widgets: ^3.3.1
  upower: ^0.7.0
  udisks: ^0.4.0
  process_run: ^0.13.3
  ini: ^2.1.0
  dbus: ^0.7.8

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/landscape_dark.png
    - assets/images/landscape_light.png
    - assets/images/getlearngive.png
    - assets/images/compudopt-icon.png
    - assets/images/compudopt-icon-white.png
    - assets/images/compudopt-logo-full.png
