name: provider_setup
description: Provider Setup Tool
publish_to: 'none'
version: 0.0.12

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  async: ^2.10.0
  flutter:
    sdk: flutter
  handy_window: ^0.3.0
  http: ^0.13.5
  meta: ^1.8.0
  provider: ^6.0.5
  safe_change_notifier: ^0.2.0
  ubuntu_service: ^0.2.0
  url_launcher: ^6.1.8
  yaru: ^0.5.0
  yaru_icons: ^1.0.2
  yaru_widgets: ^2.0.0
  upower: ^0.7.0
  process_run: ^0.12.5+2
  ini: ^2.1.0
  dbus: ^0.7.8

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/landscape_dark.png
    - assets/images/landscape_light.png
    - assets/images/getlearngive.png
    - assets/images/compudopt-icon.png
    - assets/images/compudopt-icon-white.png
    - assets/images/compudopt-logo-full.png
